#!/usr/bin/env bash

ROOT=`dirname $0`
cd ${ROOT}/..
export ROOT=$(pwd)
export PATH=${ROOT}/bin:${ROOT}/node_modules/.bin:${PATH}

PS1="\e[33m\h\e[0m:\e[32m${PROJECT}\e[0m:\w$ " $1 $2 $3 $4 $5 $6 $7 $8 $9
